config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :comments
  resources :friendships
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}


  resources :users, only: [:show, :edit, :update] do
    resources :posts do
      resources :comments
    end
  end





  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show

    @accepted_friends = Friendship.where(status: 'accepted').where("user_id = :user_id OR friend_id = :user_id", user_id: current_user.id).map do |friendship|
      friendship.user_id == current_user.id ? friendship.friend : friendship.user
    end
      
    @friendship = Friendship.new
    @post = Post.new
    @user = User.find(params[:id])
    @user_posts = Post.where(user: @user).order(created_at: :desc)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_names.html.erb
<% likes.each do |like| %>
    <%= like.user.name %><%= like == likes.last ? "" : "," %>
<% end %>

app/views/users/show.html.erb
<%#Users show %>

<div class="m-auto w-75">
        <div class="card w-100 m-auto">
       
            <div class="card-body">
            <strong>Profile</strong>
                <h1><%=@user.name%></h1>

                <p><%=@accepted_friends.count%> Friends </p>
                
                <ul class="nav float-end">
                    <%if @user == current_user%>
                        <%=button_to "Edit Profile", "#", class:"btn btn-primary mx-2"%>
                    <%else%>

                         
                                <%reciever = Friendship.find_by(user_id: @user.id, friend_id: current_user.id)%>
                                    <%requesting_friend = Friendship.find_by(user_id: current_user.id, friend_id: @user.id)%>
                                    
                                    <%if requesting_friend %>
                                        <%if requesting_friend.status=="pending"%>
                                            <%= link_to "Cancel", friendship_path(requesting_friend), data: { 'turbo-method' => :delete }, class: "btn btn-primary" %>
                                        <%else%>
                                           <%= link_to "Unfriend", friendship_path(requesting_friend), data: { 'turbo-method' => :delete }, class: "btn btn-primary" %>
                                        <%end%>
                                    <%elsif Friendship.find_by(user_id: @user.id, friend_id: current_user.id)%>
                                            <%incoming_friend = Friendship.find_by(user_id: @user.id, friend_id: current_user.id)%>
                                        <%if incoming_friend.status=="pending"%>
                                            <%= link_to "Accept", friendship_path(incoming_friend, status: "accepted"), data: { 'turbo-method' => :patch }, class:"btn mx-1 btn-primary"%>
                                            <%= link_to "Decline", friendship_path(incoming_friend), data: { 'turbo-method' => :delete }, class: "btn btn-primary" %>
                                        <%else%>
                                            <%= link_to "Unfriend", friendship_path(incoming_friend), data: { 'turbo-method' => :delete }, class: "btn btn-primary" %>
                                        <%end%>
                                    <%else%>
                                            <%=button_to "Add Friend", friendships_path(user_id: current_user.id, friend_id: @user.id, status:'pending'), class:"btn btn-primary"%>
                                    <%end%>

                                
                        
                    <%end%>
                </ul>

                
            </div>
        </div>



        <%#------------------friends------------------------------%>
        <div class="card w-25 mt-2 float-end">
        <strong class="card-body">Friends</strong>
        <div class="card-body limit">



        </div>
        </div>
        <%#------------------------------------------------%>

        
        <%#----------------------add post---------------------------------%>
        <div class="card mx-2 mt-2" style="width: 44rem;">
            
                <div class="card-body">
                
                    <%= form_with(model: @post, url: user_posts_path(current_user.id)) do |form| %>
                    <%= form.text_field :content, required: true, class: "form-control mb-3 custom-round", placeholder: "What's on your mind #{current_user.name}?" %>
                        <hr>
                        <%= form.submit 'Post', class:"btn btn-primary w-100 float-end"%>
                    <% end %>
                
                </div>
        </div>
        <%#-------------------------------------------------------------%>







        <%#------------------user posts------------------------------%>
        <div style="width: 45rem;">
        <%@user_posts.each do |post|%>
            <div class="card m-2 mb-4 shadow", style="height: 20rem">
                <div class="card-header p-3">
                    <h6> <%=post.user.name%> <span class="badge float-end bg-secondary"> <%=time_ago_in_words(post.created_at)%> ago </span></h6>

                </div>
                <div class="card-body p-4">
                <%# --------content----------- %>
                <%=post.content%>
                <%# --------content----------- %>
                </div>
                 <div class="card-header">
                    <strong class="text-primary"><%= post.likes.any? ? "Liked by #{(render "names", likes: post.likes).truncate(50)}"  : "" %></strong>
                </div>
                <div class="card-footer">
                    <ul class="nav nav-pills nav-fill">
                    <li class="nav-item">
                        
                            <%like = like_exist(post, current_user) %>
                            <%if like %>
                                <%= link_to "Like", like_path(like), data: { 'turbo-method' => :delete }, class: "btn fw-bold text-primary bi bi-hand-thumbs-up-fill" %>
                            <%else%>
                                <%= button_to "Like", likes_path(user_id: current_user.id, post_id: post.id), data: { 'turbo-method' => :post }, class: "btn fw-bold text-primary bi bi-hand-thumbs-up" %>
                            <%end%>

                    </li>
                    <li class="nav-item">
                        <%=button_to "Comment", "#", class:"btn"%>

                    </li>

                    </ul>
                </div>
            </div>

        <%end%>
        </div>
        <%#-----------------------------------------------%>
</div>