config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :comments
  resources :friendships
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}


  resources :users, only: [:show, :edit, :update] do
    resources :posts do
      resources :comments
    end
  end





  root to: "home#index"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: %i[ show edit update destroy ]

  # GET /friendships or /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1 or /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
    
  end

  # POST /friendships or /friendships.json
  def create
      @friendship = Friendship.new(user_id: params[:user_id], friend_id: params[:friend_id], status: params[:status])
    # @friendship = Friendship.new(friendship_params)

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to request.referer || root_path, notice: "Friend Request Sent." }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1 or /friendships/1.json
  def update
    @friendship = Friendship.find(params[:id])
    respond_to do |format|
      
      if @friendship.update(status: params[:status])
        format.html { redirect_to request.referer || root_path, notice: "Friendship was successfully updated." }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1 or /friendships/1.json
  def destroy
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to request.referer || root_path, notice: "Friendship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :status)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship) do |form| %>
  <% if friendship.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
        <% friendship.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :friend_id, style: "display: block" %>
    <%= form.text_field :friend_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/_friendship.html.erb
<div id="<%= dom_id friendship %>">
  <p>
    <strong>User:</strong>
    <%= friendship.user_id %>
  </p>

  <p>
    <strong>Friend:</strong>
    <%= friendship.friend_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= friendship.status %>
  </p>

</div>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Show this friendship", @friendship %> |
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friendships</h1>

<div id="friendships">
  <% @friendships.each do |friendship| %>
    <%= render friendship %>
    <p>
      <%= link_to "Show this friendship", friendship %>
    </p>
  <% end %>
</div>

<%= link_to "New friendship", new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friendship %>

<div>
  <%= link_to "Edit this friendship", edit_friendship_path(@friendship) %> |
  <%= link_to "Back to friendships", friendships_path %>

  <%= button_to "Destroy this friendship", @friendship, method: :delete %>
</div>