config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :comments
  resources :friendships
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}


  resources :users, only: [:show, :edit, :update] do
    resources :posts do
      resources :comments
    end
  end





  root to: "home#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @user = User.find(params[:user_id])
    @post = Post.where(user_id: @user.id, post_id: params[:id])
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  # GET /posts/new
  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  # POST /posts or /posts.json
  def create

    @user = User.find(params[:user_id])
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to (request.referrer || root_path), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to root_path, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to user_posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.where(id: params[:id], user_id: params[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@user, @post], url: (@post.persisted? ? user_post_path(@user, @post) : user_posts_path(@user))) do |form| %>

  <% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_names.html.erb
<% likes.each do |like| %>
    <%= like.user.name %><%= like == likes.last ? "" : "," %>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
 
    <div class="card m-2 mb-4 shadow", style="height: 20rem">
        <div class="card-header p-3">
            <h6> <%=post.user.name%> <div class="float-end"> <%= current_user == post.user ? link_to("", edit_user_post_path(user_id: current_user.id, id: post.id), class: " h5 mx-1 bi bi-pencil-square") : "" %> <span class="badge bg-secondary"> <%=time_ago_in_words(post.updated_at)%> ago </span></div>
      </h6>


        </div>
        <div class="card-body p-4">
        <%# --------content----------- %>
          <%=post.content%>
        <%# --------content----------- %>
        </div>
        <div class="card-header">
          <strong class="text-primary"><%= post.likes.any? ? "Liked by #{(render "names", likes: post.likes).truncate(50)}"  : "" %></strong>
        </div>
        <div class="card-footer">
              <ul class="nav nav-pills nav-fill">
              <li class="nav-item">


                <%like = like_exist(post, current_user) %>
                <%if like %>
                    <%= link_to "Unlike", like_path(like), data: { 'turbo-method' => :delete }, class: "btn fw-bold text-primary bi bi-hand-thumbs-up-fill" %>
                <%else%>
                    <%= button_to "Like", likes_path(user_id: current_user.id, post_id: post.id), data: { 'turbo-method' => :post }, class: "btn fw-bold text-primary bi bi-hand-thumbs-up" %>
                <%end%>


              </li>
               <li class="nav-item">
                <%=link_to "Comment","#", class:"btn"%>
              </li>
            </ul>
        </div>
    </div>

          <div class="card m-auto m-2">
              <div class="card-body">
                
                  <%= form_with(model: @comment, url: user_post_comments_path(post_id: post.id, user_id: current_user.id)) do |form| %>
                    <%= form.text_field :content, required: true, class: "form-control mb-3 custom-round", placeholder: "Leave a comment" %>
                      <hr>
                      <%= form.submit 'Comment', class:"btn btn-primary float-end"%>
                  <% end %>
              </div>
          </div>




        <%if post.comments.empty?%>

                <%else%>
                   
                    <%post.comments.each do |comment| %>
                    <div class="mb-4 mt-4">
                     <h1 class="card p-3 mx-4 bi bi-person-fill float-start"></h1>
                      <div class="card w-75">
                        <div class="card-header"><%=comment.user.name%></div>
                        <div class="card-body">
                            <%=comment.content%>
                            <%if comment.user == current_user%>
                            <%=link_to "Edit" %>
                            <%end%>
                        </div>
                      </div>
                    </div>
                    <%end%>


                <%end%>



</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", user_post_path(current_user.id, post) %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_user_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>
 
<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", user_posts_path %>
</div>

app/views/posts/show.html.erb
<%= link_to "News Feed", root_path, class:"btn btn-primary w-100" %> 
<%= render @post %>